# Generated by Django 4.2.3 on 2023-09-14 15:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/posts/images/%Y/%m/%d/')),
                ('short_description', models.TextField()),
                ('post_text', ckeditor.fields.RichTextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='postUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
