# Generated by Django 4.2.3 on 2023-09-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_usermodel_company_usermodel_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
