# Generated by Django 4.2.3 on 2023-09-15 07:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_postmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('advantages', ckeditor.fields.RichTextField()),
                ('popular', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
                'ordering': ('-id',),
            },
        ),
    ]
