# Generated by Django 4.2.3 on 2023-09-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_pricingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='recommended',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='popular',
            field=models.BooleanField(null=True),
        ),
    ]
