# Generated by Django 4.2.3 on 2023-09-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_feedbackmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
    ]
