# Generated by Django 4.2.3 on 2023-09-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
