# Generated by Django 4.2.3 on 2023-09-19 17:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_faqmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('descrption', models.TextField()),
                ('aboutthejob', ckeditor.fields.RichTextField()),
                ('responsibilities', ckeditor.fields.RichTextField()),
                ('requirements', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.jobcategorymodel')),
            ],
            options={
                'verbose_name': 'JOB OPENINGS',
                'verbose_name_plural': 'JOBS OPENINGS',
                'ordering': ('-id',),
            },
        ),
    ]
