# Generated by Django 4.2.3 on 2023-09-22 14:45

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_postmodel_category_alter_postmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Up to 16 characters. Only English letters (a-zA-Z).', max_length=16, unique=True, validators=[web.models.EnglishLettersUsernameValidator()], verbose_name='username'),
        ),
    ]
