# Generated by Django 4.2.3 on 2023-09-23 15:16

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_usermodel_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Up to 16 characters. Only English letters (a-z).', max_length=16, unique=True, validators=[web.models.EnglishLettersUsernameValidator], verbose_name='username'),
        ),
    ]
