# Generated by Django 4.2.3 on 2023-09-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='default-user.jpg', upload_to=' users/profile/profile-image/%Y/%m/%d/'),
        ),
    ]
