# Generated by Django 4.2.3 on 2023-09-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_feedbackmodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='partners/logos/<django.db.models.fields.CharField>/%Y/%m/%d/')),
            ],
        ),
    ]
