# Generated by Django 4.2.3 on 2023-09-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_partnersmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnersmodel',
            options={'ordering': ('-id',), 'verbose_name': 'PARTNER', 'verbose_name_plural': 'PARTNERS'},
        ),
    ]
