# Generated by Django 4.2.3 on 2023-09-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_partnersmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='logo',
            field=models.ImageField(upload_to='partners/logos/%Y/%m/%d/'),
        ),
    ]
