# Generated by Django 4.2.3 on 2023-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
