# Generated by Django 4.2.3 on 2023-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_jobapplymodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
