# Generated by Django 4.2.3 on 2023-09-30 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_alter_jobapplymodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[web.models.PhoneValidator()]),
        ),
        migrations.AlterField(
            model_name='jobapplymodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[web.models.PhoneValidator()]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[web.models.PhoneValidator()]),
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, validators=[web.models.PhoneValidator()])),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pricingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pricingApplyUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
