# Generated by Django 4.2.3 on 2023-09-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_alter_contactusmodel_phone_alter_jobapplymodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'ordering': ('-id',), 'verbose_name': 'PAYMENT', 'verbose_name_plural': 'PAYMENTS'},
        ),
    ]
