# Generated by Django 4.2.3 on 2023-10-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_alter_shoppingcartitem_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCartItem',
            new_name='ShoppingCartModel',
        ),
    ]
