# Generated by Django 4.2.3 on 2023-10-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_rename_shoppingcartitem_shoppingcartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcartmodel',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='shoppingcartmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.shoppingcartmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pricingmodel')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcartmodel',
            name='items',
            field=models.ManyToManyField(through='web.ShoppingCartItem', to='web.pricingmodel'),
        ),
    ]
