# Generated by Django 4.2.3 on 2023-10-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_remove_shoppingcartmodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartmodel',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shoppingcartmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
        migrations.DeleteModel(
            name='ShoppingCartModel',
        ),
    ]
