# Generated by Django 4.2.3 on 2023-10-02 11:56

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_remove_shoppingcartmodel_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13, validators=[web.models.PhoneValidator()])),
                ('email', models.EmailField(max_length=254)),
                ('total_price', models.FloatField()),
                ('socail_media', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ManyToManyField(related_name='checkout', to='web.pricingmodel')),
            ],
            options={
                'verbose_name': 'CHECKOUT',
                'verbose_name_plural': 'CHECKOUT',
            },
        ),
    ]
