# Generated by Django 4.2.3 on 2023-10-02 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_checkout_address_alter_checkout_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='checkoutUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
