# Generated by Django 4.2.3 on 2023-10-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_alter_checkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='socail_media',
            field=models.URLField(),
        ),
    ]
