# Generated by Django 4.2.3 on 2023-10-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_checkout_socail_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
