# Generated by Django 4.2.3 on 2023-10-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_delete_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='feedback_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='feedback_left',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_verified',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='web.checkout'),
        ),
    ]
