# Generated by Django 4.2.3 on 2023-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_alter_feedbackmodel_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
