# Generated by Django 4.2.3 on 2023-10-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_remove_checkout_feedback_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_verified',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='success_checkout',
            field=models.BooleanField(default=0),
        ),
    ]
