# Generated by Django 4.2.3 on 2023-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_checkout_is_verified_checkout_success_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='success_checkout',
            field=models.BooleanField(default=1),
        ),
    ]
