# Generated by Django 4.2.3 on 2023-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_alter_checkout_success_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_completed',
            field=models.BooleanField(default=0),
        ),
    ]
