# Generated by Django 4.2.3 on 2023-10-07 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_alter_faqmodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(help_text='Your password must contain at least one uppercase letter, one digit, and be at least 8 characters long.', max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.RegexValidator(message='Password can only contain English letters (a-zA-Z) and numbers (0-9).', regex='^[a-zA-Z0-9]+$')], verbose_name='password'),
        ),
    ]
