# Generated by Django 4.2.3 on 2023-10-07 14:15

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(help_text='Password must be at least 8 character and 32 long', max_length=32, validators=[web.models.PasswordValidator()], verbose_name='password'),
        ),
    ]
