# Generated by Django 4.2.3 on 2023-10-20 16:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_alter_postmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Projects Categories',
                'verbose_name_plural': 'Projects Categories',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'Checkout', 'verbose_name_plural': 'Checkout'},
        ),
        migrations.AlterModelOptions(
            name='jobmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Jobs Openings', 'verbose_name_plural': 'Jobs Openings'},
        ),
        migrations.AlterModelOptions(
            name='partnersmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Partners', 'verbose_name_plural': 'Partners'},
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='projects/images/%Y/%m/%d/')),
                ('link', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projectcategory')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
                'ordering': ('-id',),
            },
        ),
    ]
