# Generated by Django 4.2.3 on 2023-10-21 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_projectcategory_alter_checkout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
