# Generated by Django 4.2.3 on 2023-12-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_projectmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategorymodel',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='posttagmodel',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
