# Generated by Django 4.2.3 on 2023-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_alter_postcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategorymodel',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
