# Generated by Django 4.2.3 on 2023-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_alter_jobcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobKnowledgesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='location',
            field=models.CharField(default='Uzbekistan, Tashkent'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='knowledge',
            field=models.ManyToManyField(related_name='jobKnowledges', to='web.jobknowledgesmodel'),
        ),
    ]
