# Generated by Django 4.2.3 on 2023-12-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_usermodel_updated_at_alter_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='is_allowed',
            field=models.BooleanField(default=0),
        ),
    ]
