# Generated by Django 4.2.3 on 2023-12-18 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_feedbackmodel_is_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(help_text='Required. Must be a valid email address.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='default-user.jpg', upload_to='users/profile/profile-image/%Y/%m/%d/'),
        ),
    ]
