# Generated by Django 4.2.3 on 2023-12-23 11:10

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_alter_usermodel_email_alter_usermodel_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='default-user.jpg', upload_to='users/profile/profile-image/%Y/%m/%d/', validators=[web.models.validate_image_extension]),
        ),
    ]
