# Generated by Django 4.2.3 on 2023-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0077_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_private',
            field=models.BooleanField(default=0),
        ),
    ]
